export const AUTH_CONSTANTS = {
  PASSWORD_MIN_LENGTH: parseInt(process.env.PASSWORD_MIN_LENGTH || '8'),
  MAX_FAILED_LOGIN_ATTEMPTS: parseInt(process.env.MAX_FAILED_LOGIN_ATTEMPTS || '5'),
  ACCOUNT_LOCK_DURATION_MINUTES: parseInt(process.env.ACCOUNT_LOCK_DURATION_MINUTES || '10'),
  BCRYPT_ROUNDS: parseInt(process.env.BCRYPT_ROUNDS || '10'),
  JWT_SECRET: process.env.JWT_SECRET || 'change-this-secret',
  JWT_EXPIRATION: process.env.JWT_EXPIRATION || '7d',
  JWT_EXPIRATION_SECONDS: parseInt(process.env.JWT_EXPIRATION_SECONDS || '604800'), // 7 days
  GOOGLE_CLIENT_ID_MOBILE_IOS: process.env.GOOGLE_CLIENT_ID_MOBILE_IOS || '',
  GOOGLE_CLIENT_ID_MOBILE_ANDROID: process.env.GOOGLE_CLIENT_ID_MOBILE_ANDROID || '',
  GOOGLE_CLIENT_ID_PORTAL: process.env.GOOGLE_CLIENT_ID_PORTAL || '',
};
